### ISSUE TITLE
Tagged release

### ISSUE THREAD

**Issue by stevie-mayhew** [frankmullenger/silverstripe-payment-paymentexpress#7]
Hey Frank, could you take a release for this? :)

**Comment by frankmullenger** [comment]
Hey @stevie-mayhew sure, I've added you as a collaborator - please tag as you see appropriate :-) (also I think it would be good to move to Omnipay at some point what do you think?)

**Comment by stevie-mayhew** [comment]
Yes definitely. I'm working on it as we speak, definitely a better idea to rely on other people for this kind of thing ;)

I should show you through our version sometime, we've diverted quite a lot from the default SwipeStripe core and merging back up has turned out to be a nightmare so I gave up. Having the issue with our stock management module due to us having everything in 3.0.0 branches now too >_<

**Comment by frankmullenger** [comment]
True, if you could share Omnipay work that would be greatly appreciated :-)
